// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: authorization.proto
// Protobuf C++ Version: 5.27.2

#include "authorization.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace authorization {

inline constexpr CheckAuthRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : idobj_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckAuthRequest::CheckAuthRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CheckAuthRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckAuthRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckAuthRequestDefaultTypeInternal() {}
  union {
    CheckAuthRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckAuthRequestDefaultTypeInternal _CheckAuthRequest_default_instance_;

inline constexpr CheckAuthReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : typeobj_{::uint64_t{0u}},
        resultcheck_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckAuthReply::CheckAuthReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CheckAuthReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckAuthReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckAuthReplyDefaultTypeInternal() {}
  union {
    CheckAuthReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckAuthReplyDefaultTypeInternal _CheckAuthReply_default_instance_;

inline constexpr AuthObjRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : typeregister_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AuthObjRequest::AuthObjRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthObjRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthObjRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthObjRequestDefaultTypeInternal() {}
  union {
    AuthObjRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthObjRequestDefaultTypeInternal _AuthObjRequest_default_instance_;

inline constexpr AuthObjReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : idobj_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AuthObjReply::AuthObjReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AuthObjReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuthObjReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuthObjReplyDefaultTypeInternal() {}
  union {
    AuthObjReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuthObjReplyDefaultTypeInternal _AuthObjReply_default_instance_;
}  // namespace authorization
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_authorization_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_authorization_2eproto = nullptr;
const ::uint32_t
    TableStruct_authorization_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::authorization::CheckAuthRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::authorization::CheckAuthRequest, _impl_.idobj_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::authorization::CheckAuthReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::authorization::CheckAuthReply, _impl_.resultcheck_),
        PROTOBUF_FIELD_OFFSET(::authorization::CheckAuthReply, _impl_.typeobj_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::authorization::AuthObjRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::authorization::AuthObjRequest, _impl_.typeregister_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::authorization::AuthObjReply, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::authorization::AuthObjReply, _impl_.idobj_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::authorization::CheckAuthRequest)},
        {9, -1, -1, sizeof(::authorization::CheckAuthReply)},
        {19, -1, -1, sizeof(::authorization::AuthObjRequest)},
        {28, -1, -1, sizeof(::authorization::AuthObjReply)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::authorization::_CheckAuthRequest_default_instance_._instance,
    &::authorization::_CheckAuthReply_default_instance_._instance,
    &::authorization::_AuthObjRequest_default_instance_._instance,
    &::authorization::_AuthObjReply_default_instance_._instance,
};
const char descriptor_table_protodef_authorization_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023authorization.proto\022\rauthorization\"!\n\020"
    "CheckAuthRequest\022\r\n\005idObj\030\001 \001(\004\"6\n\016Check"
    "AuthReply\022\023\n\013resultCheck\030\001 \001(\010\022\017\n\007typeOb"
    "j\030\002 \001(\004\"&\n\016AuthObjRequest\022\024\n\014typeRegiste"
    "r\030\001 \001(\004\"\035\n\014AuthObjReply\022\r\n\005idObj\030\001 \001(\0042\274"
    "\001\n\rAuthorization\022Y\n\025CheckAuthorizationOb"
    "j\022\037.authorization.CheckAuthRequest\032\035.aut"
    "horization.CheckAuthReply\"\000\022P\n\020Authoriza"
    "tionObj\022\035.authorization.AuthObjRequest\032\033"
    ".authorization.AuthObjReply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_authorization_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_authorization_2eproto = {
    false,
    false,
    397,
    descriptor_table_protodef_authorization_2eproto,
    "authorization.proto",
    &descriptor_table_authorization_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_authorization_2eproto::offsets,
    file_level_enum_descriptors_authorization_2eproto,
    file_level_service_descriptors_authorization_2eproto,
};
namespace authorization {
// ===================================================================

class CheckAuthRequest::_Internal {
 public:
};

CheckAuthRequest::CheckAuthRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:authorization.CheckAuthRequest)
}
CheckAuthRequest::CheckAuthRequest(
    ::google::protobuf::Arena* arena, const CheckAuthRequest& from)
    : CheckAuthRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CheckAuthRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CheckAuthRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.idobj_ = {};
}
CheckAuthRequest::~CheckAuthRequest() {
  // @@protoc_insertion_point(destructor:authorization.CheckAuthRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CheckAuthRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CheckAuthRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CheckAuthRequest, _impl_._cached_size_),
              false,
          },
          &CheckAuthRequest::MergeImpl,
          &CheckAuthRequest::kDescriptorMethods,
          &descriptor_table_authorization_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CheckAuthRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CheckAuthRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::authorization::CheckAuthRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 idObj = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CheckAuthRequest, _impl_.idobj_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CheckAuthRequest, _impl_.idobj_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 idObj = 1;
    {PROTOBUF_FIELD_OFFSET(CheckAuthRequest, _impl_.idobj_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CheckAuthRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:authorization.CheckAuthRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.idobj_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CheckAuthRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:authorization.CheckAuthRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 idObj = 1;
  if (this->_internal_idobj() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_idobj(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:authorization.CheckAuthRequest)
  return target;
}

::size_t CheckAuthRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:authorization.CheckAuthRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 idObj = 1;
  if (this->_internal_idobj() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_idobj());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CheckAuthRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CheckAuthRequest*>(&to_msg);
  auto& from = static_cast<const CheckAuthRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:authorization.CheckAuthRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_idobj() != 0) {
    _this->_impl_.idobj_ = from._impl_.idobj_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CheckAuthRequest::CopyFrom(const CheckAuthRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:authorization.CheckAuthRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CheckAuthRequest::InternalSwap(CheckAuthRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.idobj_, other->_impl_.idobj_);
}

::google::protobuf::Metadata CheckAuthRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CheckAuthReply::_Internal {
 public:
};

CheckAuthReply::CheckAuthReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:authorization.CheckAuthReply)
}
CheckAuthReply::CheckAuthReply(
    ::google::protobuf::Arena* arena, const CheckAuthReply& from)
    : CheckAuthReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CheckAuthReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CheckAuthReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, typeobj_),
           0,
           offsetof(Impl_, resultcheck_) -
               offsetof(Impl_, typeobj_) +
               sizeof(Impl_::resultcheck_));
}
CheckAuthReply::~CheckAuthReply() {
  // @@protoc_insertion_point(destructor:authorization.CheckAuthReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CheckAuthReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CheckAuthReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CheckAuthReply, _impl_._cached_size_),
              false,
          },
          &CheckAuthReply::MergeImpl,
          &CheckAuthReply::kDescriptorMethods,
          &descriptor_table_authorization_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> CheckAuthReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_CheckAuthReply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::authorization::CheckAuthReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 typeObj = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CheckAuthReply, _impl_.typeobj_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(CheckAuthReply, _impl_.typeobj_)}},
    // bool resultCheck = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CheckAuthReply, _impl_.resultcheck_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CheckAuthReply, _impl_.resultcheck_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool resultCheck = 1;
    {PROTOBUF_FIELD_OFFSET(CheckAuthReply, _impl_.resultcheck_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // uint64 typeObj = 2;
    {PROTOBUF_FIELD_OFFSET(CheckAuthReply, _impl_.typeobj_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CheckAuthReply::Clear() {
// @@protoc_insertion_point(message_clear_start:authorization.CheckAuthReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.typeobj_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.resultcheck_) -
      reinterpret_cast<char*>(&_impl_.typeobj_)) + sizeof(_impl_.resultcheck_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CheckAuthReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:authorization.CheckAuthReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool resultCheck = 1;
  if (this->_internal_resultcheck() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_resultcheck(), target);
  }

  // uint64 typeObj = 2;
  if (this->_internal_typeobj() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        2, this->_internal_typeobj(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:authorization.CheckAuthReply)
  return target;
}

::size_t CheckAuthReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:authorization.CheckAuthReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // uint64 typeObj = 2;
  if (this->_internal_typeobj() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_typeobj());
  }

  // bool resultCheck = 1;
  if (this->_internal_resultcheck() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CheckAuthReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CheckAuthReply*>(&to_msg);
  auto& from = static_cast<const CheckAuthReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:authorization.CheckAuthReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_typeobj() != 0) {
    _this->_impl_.typeobj_ = from._impl_.typeobj_;
  }
  if (from._internal_resultcheck() != 0) {
    _this->_impl_.resultcheck_ = from._impl_.resultcheck_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CheckAuthReply::CopyFrom(const CheckAuthReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:authorization.CheckAuthReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CheckAuthReply::InternalSwap(CheckAuthReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CheckAuthReply, _impl_.resultcheck_)
      + sizeof(CheckAuthReply::_impl_.resultcheck_)
      - PROTOBUF_FIELD_OFFSET(CheckAuthReply, _impl_.typeobj_)>(
          reinterpret_cast<char*>(&_impl_.typeobj_),
          reinterpret_cast<char*>(&other->_impl_.typeobj_));
}

::google::protobuf::Metadata CheckAuthReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AuthObjRequest::_Internal {
 public:
};

AuthObjRequest::AuthObjRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:authorization.AuthObjRequest)
}
AuthObjRequest::AuthObjRequest(
    ::google::protobuf::Arena* arena, const AuthObjRequest& from)
    : AuthObjRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE AuthObjRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AuthObjRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.typeregister_ = {};
}
AuthObjRequest::~AuthObjRequest() {
  // @@protoc_insertion_point(destructor:authorization.AuthObjRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthObjRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AuthObjRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AuthObjRequest, _impl_._cached_size_),
              false,
          },
          &AuthObjRequest::MergeImpl,
          &AuthObjRequest::kDescriptorMethods,
          &descriptor_table_authorization_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> AuthObjRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AuthObjRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::authorization::AuthObjRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 typeRegister = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AuthObjRequest, _impl_.typeregister_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AuthObjRequest, _impl_.typeregister_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 typeRegister = 1;
    {PROTOBUF_FIELD_OFFSET(AuthObjRequest, _impl_.typeregister_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void AuthObjRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:authorization.AuthObjRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.typeregister_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AuthObjRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:authorization.AuthObjRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 typeRegister = 1;
  if (this->_internal_typeregister() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_typeregister(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:authorization.AuthObjRequest)
  return target;
}

::size_t AuthObjRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:authorization.AuthObjRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 typeRegister = 1;
  if (this->_internal_typeregister() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_typeregister());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AuthObjRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AuthObjRequest*>(&to_msg);
  auto& from = static_cast<const AuthObjRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:authorization.AuthObjRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_typeregister() != 0) {
    _this->_impl_.typeregister_ = from._impl_.typeregister_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthObjRequest::CopyFrom(const AuthObjRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:authorization.AuthObjRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AuthObjRequest::InternalSwap(AuthObjRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.typeregister_, other->_impl_.typeregister_);
}

::google::protobuf::Metadata AuthObjRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AuthObjReply::_Internal {
 public:
};

AuthObjReply::AuthObjReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:authorization.AuthObjReply)
}
AuthObjReply::AuthObjReply(
    ::google::protobuf::Arena* arena, const AuthObjReply& from)
    : AuthObjReply(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE AuthObjReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AuthObjReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.idobj_ = {};
}
AuthObjReply::~AuthObjReply() {
  // @@protoc_insertion_point(destructor:authorization.AuthObjReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AuthObjReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AuthObjReply::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AuthObjReply, _impl_._cached_size_),
              false,
          },
          &AuthObjReply::MergeImpl,
          &AuthObjReply::kDescriptorMethods,
          &descriptor_table_authorization_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> AuthObjReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AuthObjReply_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::authorization::AuthObjReply>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 idObj = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AuthObjReply, _impl_.idobj_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AuthObjReply, _impl_.idobj_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 idObj = 1;
    {PROTOBUF_FIELD_OFFSET(AuthObjReply, _impl_.idobj_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void AuthObjReply::Clear() {
// @@protoc_insertion_point(message_clear_start:authorization.AuthObjReply)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.idobj_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AuthObjReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:authorization.AuthObjReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 idObj = 1;
  if (this->_internal_idobj() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_idobj(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:authorization.AuthObjReply)
  return target;
}

::size_t AuthObjReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:authorization.AuthObjReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 idObj = 1;
  if (this->_internal_idobj() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_idobj());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AuthObjReply::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AuthObjReply*>(&to_msg);
  auto& from = static_cast<const AuthObjReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:authorization.AuthObjReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_idobj() != 0) {
    _this->_impl_.idobj_ = from._impl_.idobj_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AuthObjReply::CopyFrom(const AuthObjReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:authorization.AuthObjReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AuthObjReply::InternalSwap(AuthObjReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.idobj_, other->_impl_.idobj_);
}

::google::protobuf::Metadata AuthObjReply::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace authorization
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_authorization_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
