// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: router_serverGame.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_router_5fserverGame_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_router_5fserverGame_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_router_5fserverGame_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_router_5fserverGame_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_router_5fserverGame_2eproto;
namespace router_serverGame {
class AddCommandGameReply;
struct AddCommandGameReplyDefaultTypeInternal;
extern AddCommandGameReplyDefaultTypeInternal _AddCommandGameReply_default_instance_;
class AddCommandGameRequest;
struct AddCommandGameRequestDefaultTypeInternal;
extern AddCommandGameRequestDefaultTypeInternal _AddCommandGameRequest_default_instance_;
class StartNewGameReply;
struct StartNewGameReplyDefaultTypeInternal;
extern StartNewGameReplyDefaultTypeInternal _StartNewGameReply_default_instance_;
class StartNewGameRequest;
struct StartNewGameRequestDefaultTypeInternal;
extern StartNewGameRequestDefaultTypeInternal _StartNewGameRequest_default_instance_;
class StopGameReply;
struct StopGameReplyDefaultTypeInternal;
extern StopGameReplyDefaultTypeInternal _StopGameReply_default_instance_;
class StopGameRequest;
struct StopGameRequestDefaultTypeInternal;
extern StopGameRequestDefaultTypeInternal _StopGameRequest_default_instance_;
}  // namespace router_serverGame
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace router_serverGame {

// ===================================================================


// -------------------------------------------------------------------

class StopGameRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:router_serverGame.StopGameRequest) */ {
 public:
  inline StopGameRequest() : StopGameRequest(nullptr) {}
  ~StopGameRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StopGameRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline StopGameRequest(const StopGameRequest& from) : StopGameRequest(nullptr, from) {}
  inline StopGameRequest(StopGameRequest&& from) noexcept
      : StopGameRequest(nullptr, std::move(from)) {}
  inline StopGameRequest& operator=(const StopGameRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopGameRequest& operator=(StopGameRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopGameRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StopGameRequest* internal_default_instance() {
    return reinterpret_cast<const StopGameRequest*>(
        &_StopGameRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(StopGameRequest& a, StopGameRequest& b) { a.Swap(&b); }
  inline void Swap(StopGameRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopGameRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopGameRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<StopGameRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StopGameRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StopGameRequest& from) { StopGameRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StopGameRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "router_serverGame.StopGameRequest"; }

 protected:
  explicit StopGameRequest(::google::protobuf::Arena* arena);
  StopGameRequest(::google::protobuf::Arena* arena, const StopGameRequest& from);
  StopGameRequest(::google::protobuf::Arena* arena, StopGameRequest&& from) noexcept
      : StopGameRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdGameFieldNumber = 1,
  };
  // uint64 idGame = 1;
  void clear_idgame() ;
  ::uint64_t idgame() const;
  void set_idgame(::uint64_t value);

  private:
  ::uint64_t _internal_idgame() const;
  void _internal_set_idgame(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:router_serverGame.StopGameRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StopGameRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StopGameRequest& from_msg);
    ::uint64_t idgame_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_router_5fserverGame_2eproto;
};
// -------------------------------------------------------------------

class StopGameReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:router_serverGame.StopGameReply) */ {
 public:
  inline StopGameReply() : StopGameReply(nullptr) {}
  ~StopGameReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StopGameReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline StopGameReply(const StopGameReply& from) : StopGameReply(nullptr, from) {}
  inline StopGameReply(StopGameReply&& from) noexcept
      : StopGameReply(nullptr, std::move(from)) {}
  inline StopGameReply& operator=(const StopGameReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopGameReply& operator=(StopGameReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopGameReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const StopGameReply* internal_default_instance() {
    return reinterpret_cast<const StopGameReply*>(
        &_StopGameReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(StopGameReply& a, StopGameReply& b) { a.Swap(&b); }
  inline void Swap(StopGameReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopGameReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopGameReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<StopGameReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StopGameReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StopGameReply& from) { StopGameReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StopGameReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "router_serverGame.StopGameReply"; }

 protected:
  explicit StopGameReply(::google::protobuf::Arena* arena);
  StopGameReply(::google::protobuf::Arena* arena, const StopGameReply& from);
  StopGameReply(::google::protobuf::Arena* arena, StopGameReply&& from) noexcept
      : StopGameReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultCheckFieldNumber = 1,
  };
  // bool resultCheck = 1;
  void clear_resultcheck() ;
  bool resultcheck() const;
  void set_resultcheck(bool value);

  private:
  bool _internal_resultcheck() const;
  void _internal_set_resultcheck(bool value);

  public:
  // @@protoc_insertion_point(class_scope:router_serverGame.StopGameReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StopGameReply_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StopGameReply& from_msg);
    bool resultcheck_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_router_5fserverGame_2eproto;
};
// -------------------------------------------------------------------

class StartNewGameRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:router_serverGame.StartNewGameRequest) */ {
 public:
  inline StartNewGameRequest() : StartNewGameRequest(nullptr) {}
  ~StartNewGameRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StartNewGameRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline StartNewGameRequest(const StartNewGameRequest& from) : StartNewGameRequest(nullptr, from) {}
  inline StartNewGameRequest(StartNewGameRequest&& from) noexcept
      : StartNewGameRequest(nullptr, std::move(from)) {}
  inline StartNewGameRequest& operator=(const StartNewGameRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartNewGameRequest& operator=(StartNewGameRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StartNewGameRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StartNewGameRequest* internal_default_instance() {
    return reinterpret_cast<const StartNewGameRequest*>(
        &_StartNewGameRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(StartNewGameRequest& a, StartNewGameRequest& b) { a.Swap(&b); }
  inline void Swap(StartNewGameRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartNewGameRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StartNewGameRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<StartNewGameRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StartNewGameRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StartNewGameRequest& from) { StartNewGameRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StartNewGameRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "router_serverGame.StartNewGameRequest"; }

 protected:
  explicit StartNewGameRequest(::google::protobuf::Arena* arena);
  StartNewGameRequest(::google::protobuf::Arena* arena, const StartNewGameRequest& from);
  StartNewGameRequest(::google::protobuf::Arena* arena, StartNewGameRequest&& from) noexcept
      : StartNewGameRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdOtherObjFieldNumber = 3,
    kOtherArgsFieldNumber = 4,
    kIdObjFieldNumber = 1,
    kTypeRegisterFieldNumber = 2,
  };
  // string idOtherObj = 3;
  void clear_idotherobj() ;
  const std::string& idotherobj() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_idotherobj(Arg_&& arg, Args_... args);
  std::string* mutable_idotherobj();
  PROTOBUF_NODISCARD std::string* release_idotherobj();
  void set_allocated_idotherobj(std::string* value);

  private:
  const std::string& _internal_idotherobj() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_idotherobj(
      const std::string& value);
  std::string* _internal_mutable_idotherobj();

  public:
  // string otherArgs = 4;
  void clear_otherargs() ;
  const std::string& otherargs() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_otherargs(Arg_&& arg, Args_... args);
  std::string* mutable_otherargs();
  PROTOBUF_NODISCARD std::string* release_otherargs();
  void set_allocated_otherargs(std::string* value);

  private:
  const std::string& _internal_otherargs() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_otherargs(
      const std::string& value);
  std::string* _internal_mutable_otherargs();

  public:
  // uint64 idObj = 1;
  void clear_idobj() ;
  ::uint64_t idobj() const;
  void set_idobj(::uint64_t value);

  private:
  ::uint64_t _internal_idobj() const;
  void _internal_set_idobj(::uint64_t value);

  public:
  // int32 typeRegister = 2;
  void clear_typeregister() ;
  ::int32_t typeregister() const;
  void set_typeregister(::int32_t value);

  private:
  ::int32_t _internal_typeregister() const;
  void _internal_set_typeregister(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:router_serverGame.StartNewGameRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      65, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StartNewGameRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StartNewGameRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr idotherobj_;
    ::google::protobuf::internal::ArenaStringPtr otherargs_;
    ::uint64_t idobj_;
    ::int32_t typeregister_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_router_5fserverGame_2eproto;
};
// -------------------------------------------------------------------

class StartNewGameReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:router_serverGame.StartNewGameReply) */ {
 public:
  inline StartNewGameReply() : StartNewGameReply(nullptr) {}
  ~StartNewGameReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StartNewGameReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline StartNewGameReply(const StartNewGameReply& from) : StartNewGameReply(nullptr, from) {}
  inline StartNewGameReply(StartNewGameReply&& from) noexcept
      : StartNewGameReply(nullptr, std::move(from)) {}
  inline StartNewGameReply& operator=(const StartNewGameReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartNewGameReply& operator=(StartNewGameReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StartNewGameReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const StartNewGameReply* internal_default_instance() {
    return reinterpret_cast<const StartNewGameReply*>(
        &_StartNewGameReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(StartNewGameReply& a, StartNewGameReply& b) { a.Swap(&b); }
  inline void Swap(StartNewGameReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartNewGameReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StartNewGameReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<StartNewGameReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StartNewGameReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StartNewGameReply& from) { StartNewGameReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StartNewGameReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "router_serverGame.StartNewGameReply"; }

 protected:
  explicit StartNewGameReply(::google::protobuf::Arena* arena);
  StartNewGameReply(::google::protobuf::Arena* arena, const StartNewGameReply& from);
  StartNewGameReply(::google::protobuf::Arena* arena, StartNewGameReply&& from) noexcept
      : StartNewGameReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdGameFieldNumber = 2,
    kResultCheckFieldNumber = 1,
  };
  // uint64 idGame = 2;
  void clear_idgame() ;
  ::uint64_t idgame() const;
  void set_idgame(::uint64_t value);

  private:
  ::uint64_t _internal_idgame() const;
  void _internal_set_idgame(::uint64_t value);

  public:
  // bool resultCheck = 1;
  void clear_resultcheck() ;
  bool resultcheck() const;
  void set_resultcheck(bool value);

  private:
  bool _internal_resultcheck() const;
  void _internal_set_resultcheck(bool value);

  public:
  // @@protoc_insertion_point(class_scope:router_serverGame.StartNewGameReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StartNewGameReply_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StartNewGameReply& from_msg);
    ::uint64_t idgame_;
    bool resultcheck_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_router_5fserverGame_2eproto;
};
// -------------------------------------------------------------------

class AddCommandGameRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:router_serverGame.AddCommandGameRequest) */ {
 public:
  inline AddCommandGameRequest() : AddCommandGameRequest(nullptr) {}
  ~AddCommandGameRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddCommandGameRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline AddCommandGameRequest(const AddCommandGameRequest& from) : AddCommandGameRequest(nullptr, from) {}
  inline AddCommandGameRequest(AddCommandGameRequest&& from) noexcept
      : AddCommandGameRequest(nullptr, std::move(from)) {}
  inline AddCommandGameRequest& operator=(const AddCommandGameRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddCommandGameRequest& operator=(AddCommandGameRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddCommandGameRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddCommandGameRequest* internal_default_instance() {
    return reinterpret_cast<const AddCommandGameRequest*>(
        &_AddCommandGameRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(AddCommandGameRequest& a, AddCommandGameRequest& b) { a.Swap(&b); }
  inline void Swap(AddCommandGameRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddCommandGameRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddCommandGameRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AddCommandGameRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AddCommandGameRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AddCommandGameRequest& from) { AddCommandGameRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AddCommandGameRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "router_serverGame.AddCommandGameRequest"; }

 protected:
  explicit AddCommandGameRequest(::google::protobuf::Arena* arena);
  AddCommandGameRequest(::google::protobuf::Arena* arena, const AddCommandGameRequest& from);
  AddCommandGameRequest(::google::protobuf::Arena* arena, AddCommandGameRequest&& from) noexcept
      : AddCommandGameRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeCommandFieldNumber = 4,
    kArgsFieldNumber = 5,
    kIdSenderFieldNumber = 1,
    kIdGameFieldNumber = 2,
    kIdObjFieldNumber = 3,
  };
  // string TypeCommand = 4;
  void clear_typecommand() ;
  const std::string& typecommand() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_typecommand(Arg_&& arg, Args_... args);
  std::string* mutable_typecommand();
  PROTOBUF_NODISCARD std::string* release_typecommand();
  void set_allocated_typecommand(std::string* value);

  private:
  const std::string& _internal_typecommand() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_typecommand(
      const std::string& value);
  std::string* _internal_mutable_typecommand();

  public:
  // string args = 5;
  void clear_args() ;
  const std::string& args() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_args(Arg_&& arg, Args_... args);
  std::string* mutable_args();
  PROTOBUF_NODISCARD std::string* release_args();
  void set_allocated_args(std::string* value);

  private:
  const std::string& _internal_args() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_args(
      const std::string& value);
  std::string* _internal_mutable_args();

  public:
  // uint64 idSender = 1;
  void clear_idsender() ;
  ::uint64_t idsender() const;
  void set_idsender(::uint64_t value);

  private:
  ::uint64_t _internal_idsender() const;
  void _internal_set_idsender(::uint64_t value);

  public:
  // uint64 idGame = 2;
  void clear_idgame() ;
  ::uint64_t idgame() const;
  void set_idgame(::uint64_t value);

  private:
  ::uint64_t _internal_idgame() const;
  void _internal_set_idgame(::uint64_t value);

  public:
  // uint64 idObj = 3;
  void clear_idobj() ;
  ::uint64_t idobj() const;
  void set_idobj(::uint64_t value);

  private:
  ::uint64_t _internal_idobj() const;
  void _internal_set_idobj(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:router_serverGame.AddCommandGameRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      63, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AddCommandGameRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AddCommandGameRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr typecommand_;
    ::google::protobuf::internal::ArenaStringPtr args_;
    ::uint64_t idsender_;
    ::uint64_t idgame_;
    ::uint64_t idobj_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_router_5fserverGame_2eproto;
};
// -------------------------------------------------------------------

class AddCommandGameReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:router_serverGame.AddCommandGameReply) */ {
 public:
  inline AddCommandGameReply() : AddCommandGameReply(nullptr) {}
  ~AddCommandGameReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddCommandGameReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline AddCommandGameReply(const AddCommandGameReply& from) : AddCommandGameReply(nullptr, from) {}
  inline AddCommandGameReply(AddCommandGameReply&& from) noexcept
      : AddCommandGameReply(nullptr, std::move(from)) {}
  inline AddCommandGameReply& operator=(const AddCommandGameReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddCommandGameReply& operator=(AddCommandGameReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddCommandGameReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddCommandGameReply* internal_default_instance() {
    return reinterpret_cast<const AddCommandGameReply*>(
        &_AddCommandGameReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(AddCommandGameReply& a, AddCommandGameReply& b) { a.Swap(&b); }
  inline void Swap(AddCommandGameReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddCommandGameReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddCommandGameReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AddCommandGameReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AddCommandGameReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AddCommandGameReply& from) { AddCommandGameReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AddCommandGameReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "router_serverGame.AddCommandGameReply"; }

 protected:
  explicit AddCommandGameReply(::google::protobuf::Arena* arena);
  AddCommandGameReply(::google::protobuf::Arena* arena, const AddCommandGameReply& from);
  AddCommandGameReply(::google::protobuf::Arena* arena, AddCommandGameReply&& from) noexcept
      : AddCommandGameReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjParamsFieldNumber = 1,
  };
  // string objParams = 1;
  void clear_objparams() ;
  const std::string& objparams() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_objparams(Arg_&& arg, Args_... args);
  std::string* mutable_objparams();
  PROTOBUF_NODISCARD std::string* release_objparams();
  void set_allocated_objparams(std::string* value);

  private:
  const std::string& _internal_objparams() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_objparams(
      const std::string& value);
  std::string* _internal_mutable_objparams();

  public:
  // @@protoc_insertion_point(class_scope:router_serverGame.AddCommandGameReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      55, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AddCommandGameReply_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AddCommandGameReply& from_msg);
    ::google::protobuf::internal::ArenaStringPtr objparams_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_router_5fserverGame_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StartNewGameRequest

// uint64 idObj = 1;
inline void StartNewGameRequest::clear_idobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = ::uint64_t{0u};
}
inline ::uint64_t StartNewGameRequest::idobj() const {
  // @@protoc_insertion_point(field_get:router_serverGame.StartNewGameRequest.idObj)
  return _internal_idobj();
}
inline void StartNewGameRequest::set_idobj(::uint64_t value) {
  _internal_set_idobj(value);
  // @@protoc_insertion_point(field_set:router_serverGame.StartNewGameRequest.idObj)
}
inline ::uint64_t StartNewGameRequest::_internal_idobj() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idobj_;
}
inline void StartNewGameRequest::_internal_set_idobj(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = value;
}

// int32 typeRegister = 2;
inline void StartNewGameRequest::clear_typeregister() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typeregister_ = 0;
}
inline ::int32_t StartNewGameRequest::typeregister() const {
  // @@protoc_insertion_point(field_get:router_serverGame.StartNewGameRequest.typeRegister)
  return _internal_typeregister();
}
inline void StartNewGameRequest::set_typeregister(::int32_t value) {
  _internal_set_typeregister(value);
  // @@protoc_insertion_point(field_set:router_serverGame.StartNewGameRequest.typeRegister)
}
inline ::int32_t StartNewGameRequest::_internal_typeregister() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.typeregister_;
}
inline void StartNewGameRequest::_internal_set_typeregister(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typeregister_ = value;
}

// string idOtherObj = 3;
inline void StartNewGameRequest::clear_idotherobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idotherobj_.ClearToEmpty();
}
inline const std::string& StartNewGameRequest::idotherobj() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:router_serverGame.StartNewGameRequest.idOtherObj)
  return _internal_idotherobj();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void StartNewGameRequest::set_idotherobj(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idotherobj_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:router_serverGame.StartNewGameRequest.idOtherObj)
}
inline std::string* StartNewGameRequest::mutable_idotherobj() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_idotherobj();
  // @@protoc_insertion_point(field_mutable:router_serverGame.StartNewGameRequest.idOtherObj)
  return _s;
}
inline const std::string& StartNewGameRequest::_internal_idotherobj() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idotherobj_.Get();
}
inline void StartNewGameRequest::_internal_set_idotherobj(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idotherobj_.Set(value, GetArena());
}
inline std::string* StartNewGameRequest::_internal_mutable_idotherobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.idotherobj_.Mutable( GetArena());
}
inline std::string* StartNewGameRequest::release_idotherobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:router_serverGame.StartNewGameRequest.idOtherObj)
  return _impl_.idotherobj_.Release();
}
inline void StartNewGameRequest::set_allocated_idotherobj(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idotherobj_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.idotherobj_.IsDefault()) {
          _impl_.idotherobj_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:router_serverGame.StartNewGameRequest.idOtherObj)
}

// string otherArgs = 4;
inline void StartNewGameRequest::clear_otherargs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.otherargs_.ClearToEmpty();
}
inline const std::string& StartNewGameRequest::otherargs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:router_serverGame.StartNewGameRequest.otherArgs)
  return _internal_otherargs();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void StartNewGameRequest::set_otherargs(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.otherargs_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:router_serverGame.StartNewGameRequest.otherArgs)
}
inline std::string* StartNewGameRequest::mutable_otherargs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_otherargs();
  // @@protoc_insertion_point(field_mutable:router_serverGame.StartNewGameRequest.otherArgs)
  return _s;
}
inline const std::string& StartNewGameRequest::_internal_otherargs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.otherargs_.Get();
}
inline void StartNewGameRequest::_internal_set_otherargs(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.otherargs_.Set(value, GetArena());
}
inline std::string* StartNewGameRequest::_internal_mutable_otherargs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.otherargs_.Mutable( GetArena());
}
inline std::string* StartNewGameRequest::release_otherargs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:router_serverGame.StartNewGameRequest.otherArgs)
  return _impl_.otherargs_.Release();
}
inline void StartNewGameRequest::set_allocated_otherargs(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.otherargs_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.otherargs_.IsDefault()) {
          _impl_.otherargs_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:router_serverGame.StartNewGameRequest.otherArgs)
}

// -------------------------------------------------------------------

// StartNewGameReply

// bool resultCheck = 1;
inline void StartNewGameReply::clear_resultcheck() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resultcheck_ = false;
}
inline bool StartNewGameReply::resultcheck() const {
  // @@protoc_insertion_point(field_get:router_serverGame.StartNewGameReply.resultCheck)
  return _internal_resultcheck();
}
inline void StartNewGameReply::set_resultcheck(bool value) {
  _internal_set_resultcheck(value);
  // @@protoc_insertion_point(field_set:router_serverGame.StartNewGameReply.resultCheck)
}
inline bool StartNewGameReply::_internal_resultcheck() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resultcheck_;
}
inline void StartNewGameReply::_internal_set_resultcheck(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resultcheck_ = value;
}

// uint64 idGame = 2;
inline void StartNewGameReply::clear_idgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = ::uint64_t{0u};
}
inline ::uint64_t StartNewGameReply::idgame() const {
  // @@protoc_insertion_point(field_get:router_serverGame.StartNewGameReply.idGame)
  return _internal_idgame();
}
inline void StartNewGameReply::set_idgame(::uint64_t value) {
  _internal_set_idgame(value);
  // @@protoc_insertion_point(field_set:router_serverGame.StartNewGameReply.idGame)
}
inline ::uint64_t StartNewGameReply::_internal_idgame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idgame_;
}
inline void StartNewGameReply::_internal_set_idgame(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = value;
}

// -------------------------------------------------------------------

// AddCommandGameRequest

// uint64 idSender = 1;
inline void AddCommandGameRequest::clear_idsender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idsender_ = ::uint64_t{0u};
}
inline ::uint64_t AddCommandGameRequest::idsender() const {
  // @@protoc_insertion_point(field_get:router_serverGame.AddCommandGameRequest.idSender)
  return _internal_idsender();
}
inline void AddCommandGameRequest::set_idsender(::uint64_t value) {
  _internal_set_idsender(value);
  // @@protoc_insertion_point(field_set:router_serverGame.AddCommandGameRequest.idSender)
}
inline ::uint64_t AddCommandGameRequest::_internal_idsender() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idsender_;
}
inline void AddCommandGameRequest::_internal_set_idsender(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idsender_ = value;
}

// uint64 idGame = 2;
inline void AddCommandGameRequest::clear_idgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = ::uint64_t{0u};
}
inline ::uint64_t AddCommandGameRequest::idgame() const {
  // @@protoc_insertion_point(field_get:router_serverGame.AddCommandGameRequest.idGame)
  return _internal_idgame();
}
inline void AddCommandGameRequest::set_idgame(::uint64_t value) {
  _internal_set_idgame(value);
  // @@protoc_insertion_point(field_set:router_serverGame.AddCommandGameRequest.idGame)
}
inline ::uint64_t AddCommandGameRequest::_internal_idgame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idgame_;
}
inline void AddCommandGameRequest::_internal_set_idgame(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = value;
}

// uint64 idObj = 3;
inline void AddCommandGameRequest::clear_idobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = ::uint64_t{0u};
}
inline ::uint64_t AddCommandGameRequest::idobj() const {
  // @@protoc_insertion_point(field_get:router_serverGame.AddCommandGameRequest.idObj)
  return _internal_idobj();
}
inline void AddCommandGameRequest::set_idobj(::uint64_t value) {
  _internal_set_idobj(value);
  // @@protoc_insertion_point(field_set:router_serverGame.AddCommandGameRequest.idObj)
}
inline ::uint64_t AddCommandGameRequest::_internal_idobj() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idobj_;
}
inline void AddCommandGameRequest::_internal_set_idobj(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = value;
}

// string TypeCommand = 4;
inline void AddCommandGameRequest::clear_typecommand() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typecommand_.ClearToEmpty();
}
inline const std::string& AddCommandGameRequest::typecommand() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:router_serverGame.AddCommandGameRequest.TypeCommand)
  return _internal_typecommand();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AddCommandGameRequest::set_typecommand(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typecommand_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:router_serverGame.AddCommandGameRequest.TypeCommand)
}
inline std::string* AddCommandGameRequest::mutable_typecommand() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_typecommand();
  // @@protoc_insertion_point(field_mutable:router_serverGame.AddCommandGameRequest.TypeCommand)
  return _s;
}
inline const std::string& AddCommandGameRequest::_internal_typecommand() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.typecommand_.Get();
}
inline void AddCommandGameRequest::_internal_set_typecommand(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typecommand_.Set(value, GetArena());
}
inline std::string* AddCommandGameRequest::_internal_mutable_typecommand() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.typecommand_.Mutable( GetArena());
}
inline std::string* AddCommandGameRequest::release_typecommand() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:router_serverGame.AddCommandGameRequest.TypeCommand)
  return _impl_.typecommand_.Release();
}
inline void AddCommandGameRequest::set_allocated_typecommand(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typecommand_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.typecommand_.IsDefault()) {
          _impl_.typecommand_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:router_serverGame.AddCommandGameRequest.TypeCommand)
}

// string args = 5;
inline void AddCommandGameRequest::clear_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.args_.ClearToEmpty();
}
inline const std::string& AddCommandGameRequest::args() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:router_serverGame.AddCommandGameRequest.args)
  return _internal_args();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AddCommandGameRequest::set_args(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.args_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:router_serverGame.AddCommandGameRequest.args)
}
inline std::string* AddCommandGameRequest::mutable_args() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_args();
  // @@protoc_insertion_point(field_mutable:router_serverGame.AddCommandGameRequest.args)
  return _s;
}
inline const std::string& AddCommandGameRequest::_internal_args() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.args_.Get();
}
inline void AddCommandGameRequest::_internal_set_args(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.args_.Set(value, GetArena());
}
inline std::string* AddCommandGameRequest::_internal_mutable_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.args_.Mutable( GetArena());
}
inline std::string* AddCommandGameRequest::release_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:router_serverGame.AddCommandGameRequest.args)
  return _impl_.args_.Release();
}
inline void AddCommandGameRequest::set_allocated_args(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.args_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.args_.IsDefault()) {
          _impl_.args_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:router_serverGame.AddCommandGameRequest.args)
}

// -------------------------------------------------------------------

// AddCommandGameReply

// string objParams = 1;
inline void AddCommandGameReply::clear_objparams() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objparams_.ClearToEmpty();
}
inline const std::string& AddCommandGameReply::objparams() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:router_serverGame.AddCommandGameReply.objParams)
  return _internal_objparams();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AddCommandGameReply::set_objparams(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objparams_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:router_serverGame.AddCommandGameReply.objParams)
}
inline std::string* AddCommandGameReply::mutable_objparams() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_objparams();
  // @@protoc_insertion_point(field_mutable:router_serverGame.AddCommandGameReply.objParams)
  return _s;
}
inline const std::string& AddCommandGameReply::_internal_objparams() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.objparams_.Get();
}
inline void AddCommandGameReply::_internal_set_objparams(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objparams_.Set(value, GetArena());
}
inline std::string* AddCommandGameReply::_internal_mutable_objparams() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.objparams_.Mutable( GetArena());
}
inline std::string* AddCommandGameReply::release_objparams() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:router_serverGame.AddCommandGameReply.objParams)
  return _impl_.objparams_.Release();
}
inline void AddCommandGameReply::set_allocated_objparams(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objparams_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.objparams_.IsDefault()) {
          _impl_.objparams_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:router_serverGame.AddCommandGameReply.objParams)
}

// -------------------------------------------------------------------

// StopGameRequest

// uint64 idGame = 1;
inline void StopGameRequest::clear_idgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = ::uint64_t{0u};
}
inline ::uint64_t StopGameRequest::idgame() const {
  // @@protoc_insertion_point(field_get:router_serverGame.StopGameRequest.idGame)
  return _internal_idgame();
}
inline void StopGameRequest::set_idgame(::uint64_t value) {
  _internal_set_idgame(value);
  // @@protoc_insertion_point(field_set:router_serverGame.StopGameRequest.idGame)
}
inline ::uint64_t StopGameRequest::_internal_idgame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idgame_;
}
inline void StopGameRequest::_internal_set_idgame(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = value;
}

// -------------------------------------------------------------------

// StopGameReply

// bool resultCheck = 1;
inline void StopGameReply::clear_resultcheck() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resultcheck_ = false;
}
inline bool StopGameReply::resultcheck() const {
  // @@protoc_insertion_point(field_get:router_serverGame.StopGameReply.resultCheck)
  return _internal_resultcheck();
}
inline void StopGameReply::set_resultcheck(bool value) {
  _internal_set_resultcheck(value);
  // @@protoc_insertion_point(field_set:router_serverGame.StopGameReply.resultCheck)
}
inline bool StopGameReply::_internal_resultcheck() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resultcheck_;
}
inline void StopGameReply::_internal_set_resultcheck(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resultcheck_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace router_serverGame


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_router_5fserverGame_2eproto_2epb_2eh
