// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: client_router.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_client_5frouter_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_client_5frouter_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_client_5frouter_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_client_5frouter_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_client_5frouter_2eproto;
namespace client_router {
class AddCommandGameRReply;
struct AddCommandGameRReplyDefaultTypeInternal;
extern AddCommandGameRReplyDefaultTypeInternal _AddCommandGameRReply_default_instance_;
class AddCommandGameRRequest;
struct AddCommandGameRRequestDefaultTypeInternal;
extern AddCommandGameRRequestDefaultTypeInternal _AddCommandGameRRequest_default_instance_;
class AuthObjRReply;
struct AuthObjRReplyDefaultTypeInternal;
extern AuthObjRReplyDefaultTypeInternal _AuthObjRReply_default_instance_;
class AuthObjRRequest;
struct AuthObjRRequestDefaultTypeInternal;
extern AuthObjRRequestDefaultTypeInternal _AuthObjRRequest_default_instance_;
class GetInfGameRReply;
struct GetInfGameRReplyDefaultTypeInternal;
extern GetInfGameRReplyDefaultTypeInternal _GetInfGameRReply_default_instance_;
class GetInfGameRRequest;
struct GetInfGameRRequestDefaultTypeInternal;
extern GetInfGameRRequestDefaultTypeInternal _GetInfGameRRequest_default_instance_;
class StartNewGameRReply;
struct StartNewGameRReplyDefaultTypeInternal;
extern StartNewGameRReplyDefaultTypeInternal _StartNewGameRReply_default_instance_;
class StartNewGameRRequest;
struct StartNewGameRRequestDefaultTypeInternal;
extern StartNewGameRRequestDefaultTypeInternal _StartNewGameRRequest_default_instance_;
class StopGameRReply;
struct StopGameRReplyDefaultTypeInternal;
extern StopGameRReplyDefaultTypeInternal _StopGameRReply_default_instance_;
class StopGameRRequest;
struct StopGameRRequestDefaultTypeInternal;
extern StopGameRRequestDefaultTypeInternal _StopGameRRequest_default_instance_;
}  // namespace client_router
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace client_router {

// ===================================================================


// -------------------------------------------------------------------

class StopGameRRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.StopGameRRequest) */ {
 public:
  inline StopGameRRequest() : StopGameRRequest(nullptr) {}
  ~StopGameRRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StopGameRRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline StopGameRRequest(const StopGameRRequest& from) : StopGameRRequest(nullptr, from) {}
  inline StopGameRRequest(StopGameRRequest&& from) noexcept
      : StopGameRRequest(nullptr, std::move(from)) {}
  inline StopGameRRequest& operator=(const StopGameRRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopGameRRequest& operator=(StopGameRRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopGameRRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StopGameRRequest* internal_default_instance() {
    return reinterpret_cast<const StopGameRRequest*>(
        &_StopGameRRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(StopGameRRequest& a, StopGameRRequest& b) { a.Swap(&b); }
  inline void Swap(StopGameRRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopGameRRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopGameRRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<StopGameRRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StopGameRRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StopGameRRequest& from) { StopGameRRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StopGameRRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.StopGameRRequest"; }

 protected:
  explicit StopGameRRequest(::google::protobuf::Arena* arena);
  StopGameRRequest(::google::protobuf::Arena* arena, const StopGameRRequest& from);
  StopGameRRequest(::google::protobuf::Arena* arena, StopGameRRequest&& from) noexcept
      : StopGameRRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdSenderFieldNumber = 1,
    kIdGameFieldNumber = 2,
  };
  // uint64 idSender = 1;
  void clear_idsender() ;
  ::uint64_t idsender() const;
  void set_idsender(::uint64_t value);

  private:
  ::uint64_t _internal_idsender() const;
  void _internal_set_idsender(::uint64_t value);

  public:
  // uint64 idGame = 2;
  void clear_idgame() ;
  ::uint64_t idgame() const;
  void set_idgame(::uint64_t value);

  private:
  ::uint64_t _internal_idgame() const;
  void _internal_set_idgame(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:client_router.StopGameRRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StopGameRRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StopGameRRequest& from_msg);
    ::uint64_t idsender_;
    ::uint64_t idgame_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};
// -------------------------------------------------------------------

class StopGameRReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.StopGameRReply) */ {
 public:
  inline StopGameRReply() : StopGameRReply(nullptr) {}
  ~StopGameRReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StopGameRReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline StopGameRReply(const StopGameRReply& from) : StopGameRReply(nullptr, from) {}
  inline StopGameRReply(StopGameRReply&& from) noexcept
      : StopGameRReply(nullptr, std::move(from)) {}
  inline StopGameRReply& operator=(const StopGameRReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline StopGameRReply& operator=(StopGameRReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StopGameRReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const StopGameRReply* internal_default_instance() {
    return reinterpret_cast<const StopGameRReply*>(
        &_StopGameRReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(StopGameRReply& a, StopGameRReply& b) { a.Swap(&b); }
  inline void Swap(StopGameRReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StopGameRReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StopGameRReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<StopGameRReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StopGameRReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StopGameRReply& from) { StopGameRReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StopGameRReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.StopGameRReply"; }

 protected:
  explicit StopGameRReply(::google::protobuf::Arena* arena);
  StopGameRReply(::google::protobuf::Arena* arena, const StopGameRReply& from);
  StopGameRReply(::google::protobuf::Arena* arena, StopGameRReply&& from) noexcept
      : StopGameRReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResultCheckFieldNumber = 1,
  };
  // bool resultCheck = 1;
  void clear_resultcheck() ;
  bool resultcheck() const;
  void set_resultcheck(bool value);

  private:
  bool _internal_resultcheck() const;
  void _internal_set_resultcheck(bool value);

  public:
  // @@protoc_insertion_point(class_scope:client_router.StopGameRReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StopGameRReply_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StopGameRReply& from_msg);
    bool resultcheck_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};
// -------------------------------------------------------------------

class StartNewGameRRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.StartNewGameRRequest) */ {
 public:
  inline StartNewGameRRequest() : StartNewGameRRequest(nullptr) {}
  ~StartNewGameRRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StartNewGameRRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline StartNewGameRRequest(const StartNewGameRRequest& from) : StartNewGameRRequest(nullptr, from) {}
  inline StartNewGameRRequest(StartNewGameRRequest&& from) noexcept
      : StartNewGameRRequest(nullptr, std::move(from)) {}
  inline StartNewGameRRequest& operator=(const StartNewGameRRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartNewGameRRequest& operator=(StartNewGameRRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StartNewGameRRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const StartNewGameRRequest* internal_default_instance() {
    return reinterpret_cast<const StartNewGameRRequest*>(
        &_StartNewGameRRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(StartNewGameRRequest& a, StartNewGameRRequest& b) { a.Swap(&b); }
  inline void Swap(StartNewGameRRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartNewGameRRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StartNewGameRRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<StartNewGameRRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StartNewGameRRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StartNewGameRRequest& from) { StartNewGameRRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StartNewGameRRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.StartNewGameRRequest"; }

 protected:
  explicit StartNewGameRRequest(::google::protobuf::Arena* arena);
  StartNewGameRRequest(::google::protobuf::Arena* arena, const StartNewGameRRequest& from);
  StartNewGameRRequest(::google::protobuf::Arena* arena, StartNewGameRRequest&& from) noexcept
      : StartNewGameRRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdOtherObjFieldNumber = 3,
    kOtherArgsFieldNumber = 4,
    kIdObjFieldNumber = 1,
  };
  // string idOtherObj = 3;
  void clear_idotherobj() ;
  const std::string& idotherobj() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_idotherobj(Arg_&& arg, Args_... args);
  std::string* mutable_idotherobj();
  PROTOBUF_NODISCARD std::string* release_idotherobj();
  void set_allocated_idotherobj(std::string* value);

  private:
  const std::string& _internal_idotherobj() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_idotherobj(
      const std::string& value);
  std::string* _internal_mutable_idotherobj();

  public:
  // string otherArgs = 4;
  void clear_otherargs() ;
  const std::string& otherargs() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_otherargs(Arg_&& arg, Args_... args);
  std::string* mutable_otherargs();
  PROTOBUF_NODISCARD std::string* release_otherargs();
  void set_allocated_otherargs(std::string* value);

  private:
  const std::string& _internal_otherargs() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_otherargs(
      const std::string& value);
  std::string* _internal_mutable_otherargs();

  public:
  // uint64 idObj = 1;
  void clear_idobj() ;
  ::uint64_t idobj() const;
  void set_idobj(::uint64_t value);

  private:
  ::uint64_t _internal_idobj() const;
  void _internal_set_idobj(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:client_router.StartNewGameRRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      62, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StartNewGameRRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StartNewGameRRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr idotherobj_;
    ::google::protobuf::internal::ArenaStringPtr otherargs_;
    ::uint64_t idobj_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};
// -------------------------------------------------------------------

class StartNewGameRReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.StartNewGameRReply) */ {
 public:
  inline StartNewGameRReply() : StartNewGameRReply(nullptr) {}
  ~StartNewGameRReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR StartNewGameRReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline StartNewGameRReply(const StartNewGameRReply& from) : StartNewGameRReply(nullptr, from) {}
  inline StartNewGameRReply(StartNewGameRReply&& from) noexcept
      : StartNewGameRReply(nullptr, std::move(from)) {}
  inline StartNewGameRReply& operator=(const StartNewGameRReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartNewGameRReply& operator=(StartNewGameRReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StartNewGameRReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const StartNewGameRReply* internal_default_instance() {
    return reinterpret_cast<const StartNewGameRReply*>(
        &_StartNewGameRReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(StartNewGameRReply& a, StartNewGameRReply& b) { a.Swap(&b); }
  inline void Swap(StartNewGameRReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartNewGameRReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StartNewGameRReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<StartNewGameRReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StartNewGameRReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StartNewGameRReply& from) { StartNewGameRReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(StartNewGameRReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.StartNewGameRReply"; }

 protected:
  explicit StartNewGameRReply(::google::protobuf::Arena* arena);
  StartNewGameRReply(::google::protobuf::Arena* arena, const StartNewGameRReply& from);
  StartNewGameRReply(::google::protobuf::Arena* arena, StartNewGameRReply&& from) noexcept
      : StartNewGameRReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdGameFieldNumber = 2,
    kResultCheckFieldNumber = 1,
  };
  // uint64 idGame = 2;
  void clear_idgame() ;
  ::uint64_t idgame() const;
  void set_idgame(::uint64_t value);

  private:
  ::uint64_t _internal_idgame() const;
  void _internal_set_idgame(::uint64_t value);

  public:
  // bool resultCheck = 1;
  void clear_resultcheck() ;
  bool resultcheck() const;
  void set_resultcheck(bool value);

  private:
  bool _internal_resultcheck() const;
  void _internal_set_resultcheck(bool value);

  public:
  // @@protoc_insertion_point(class_scope:client_router.StartNewGameRReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_StartNewGameRReply_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const StartNewGameRReply& from_msg);
    ::uint64_t idgame_;
    bool resultcheck_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};
// -------------------------------------------------------------------

class GetInfGameRRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.GetInfGameRRequest) */ {
 public:
  inline GetInfGameRRequest() : GetInfGameRRequest(nullptr) {}
  ~GetInfGameRRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetInfGameRRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetInfGameRRequest(const GetInfGameRRequest& from) : GetInfGameRRequest(nullptr, from) {}
  inline GetInfGameRRequest(GetInfGameRRequest&& from) noexcept
      : GetInfGameRRequest(nullptr, std::move(from)) {}
  inline GetInfGameRRequest& operator=(const GetInfGameRRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetInfGameRRequest& operator=(GetInfGameRRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetInfGameRRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetInfGameRRequest* internal_default_instance() {
    return reinterpret_cast<const GetInfGameRRequest*>(
        &_GetInfGameRRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 8;
  friend void swap(GetInfGameRRequest& a, GetInfGameRRequest& b) { a.Swap(&b); }
  inline void Swap(GetInfGameRRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetInfGameRRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetInfGameRRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<GetInfGameRRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetInfGameRRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetInfGameRRequest& from) { GetInfGameRRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GetInfGameRRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.GetInfGameRRequest"; }

 protected:
  explicit GetInfGameRRequest(::google::protobuf::Arena* arena);
  GetInfGameRRequest(::google::protobuf::Arena* arena, const GetInfGameRRequest& from);
  GetInfGameRRequest(::google::protobuf::Arena* arena, GetInfGameRRequest&& from) noexcept
      : GetInfGameRRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdGameFieldNumber = 1,
  };
  // uint64 idGame = 1;
  void clear_idgame() ;
  ::uint64_t idgame() const;
  void set_idgame(::uint64_t value);

  private:
  ::uint64_t _internal_idgame() const;
  void _internal_set_idgame(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:client_router.GetInfGameRRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_GetInfGameRRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetInfGameRRequest& from_msg);
    ::uint64_t idgame_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};
// -------------------------------------------------------------------

class GetInfGameRReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.GetInfGameRReply) */ {
 public:
  inline GetInfGameRReply() : GetInfGameRReply(nullptr) {}
  ~GetInfGameRReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetInfGameRReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline GetInfGameRReply(const GetInfGameRReply& from) : GetInfGameRReply(nullptr, from) {}
  inline GetInfGameRReply(GetInfGameRReply&& from) noexcept
      : GetInfGameRReply(nullptr, std::move(from)) {}
  inline GetInfGameRReply& operator=(const GetInfGameRReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetInfGameRReply& operator=(GetInfGameRReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetInfGameRReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetInfGameRReply* internal_default_instance() {
    return reinterpret_cast<const GetInfGameRReply*>(
        &_GetInfGameRReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 9;
  friend void swap(GetInfGameRReply& a, GetInfGameRReply& b) { a.Swap(&b); }
  inline void Swap(GetInfGameRReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetInfGameRReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetInfGameRReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<GetInfGameRReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetInfGameRReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetInfGameRReply& from) { GetInfGameRReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(GetInfGameRReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.GetInfGameRReply"; }

 protected:
  explicit GetInfGameRReply(::google::protobuf::Arena* arena);
  GetInfGameRReply(::google::protobuf::Arena* arena, const GetInfGameRReply& from);
  GetInfGameRReply(::google::protobuf::Arena* arena, GetInfGameRReply&& from) noexcept
      : GetInfGameRReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kInfGameFieldNumber = 1,
  };
  // string infGame = 1;
  void clear_infgame() ;
  const std::string& infgame() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_infgame(Arg_&& arg, Args_... args);
  std::string* mutable_infgame();
  PROTOBUF_NODISCARD std::string* release_infgame();
  void set_allocated_infgame(std::string* value);

  private:
  const std::string& _internal_infgame() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_infgame(
      const std::string& value);
  std::string* _internal_mutable_infgame();

  public:
  // @@protoc_insertion_point(class_scope:client_router.GetInfGameRReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      46, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_GetInfGameRReply_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GetInfGameRReply& from_msg);
    ::google::protobuf::internal::ArenaStringPtr infgame_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};
// -------------------------------------------------------------------

class AuthObjRRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.AuthObjRRequest) */ {
 public:
  inline AuthObjRRequest() : AuthObjRRequest(nullptr) {}
  ~AuthObjRRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AuthObjRRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline AuthObjRRequest(const AuthObjRRequest& from) : AuthObjRRequest(nullptr, from) {}
  inline AuthObjRRequest(AuthObjRRequest&& from) noexcept
      : AuthObjRRequest(nullptr, std::move(from)) {}
  inline AuthObjRRequest& operator=(const AuthObjRRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthObjRRequest& operator=(AuthObjRRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthObjRRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuthObjRRequest* internal_default_instance() {
    return reinterpret_cast<const AuthObjRRequest*>(
        &_AuthObjRRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(AuthObjRRequest& a, AuthObjRRequest& b) { a.Swap(&b); }
  inline void Swap(AuthObjRRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthObjRRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthObjRRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AuthObjRRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AuthObjRRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AuthObjRRequest& from) { AuthObjRRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AuthObjRRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.AuthObjRRequest"; }

 protected:
  explicit AuthObjRRequest(::google::protobuf::Arena* arena);
  AuthObjRRequest(::google::protobuf::Arena* arena, const AuthObjRRequest& from);
  AuthObjRRequest(::google::protobuf::Arena* arena, AuthObjRRequest&& from) noexcept
      : AuthObjRRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeRegisterFieldNumber = 1,
  };
  // int32 typeRegister = 1;
  void clear_typeregister() ;
  ::int32_t typeregister() const;
  void set_typeregister(::int32_t value);

  private:
  ::int32_t _internal_typeregister() const;
  void _internal_set_typeregister(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:client_router.AuthObjRRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AuthObjRRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AuthObjRRequest& from_msg);
    ::int32_t typeregister_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};
// -------------------------------------------------------------------

class AuthObjRReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.AuthObjRReply) */ {
 public:
  inline AuthObjRReply() : AuthObjRReply(nullptr) {}
  ~AuthObjRReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AuthObjRReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline AuthObjRReply(const AuthObjRReply& from) : AuthObjRReply(nullptr, from) {}
  inline AuthObjRReply(AuthObjRReply&& from) noexcept
      : AuthObjRReply(nullptr, std::move(from)) {}
  inline AuthObjRReply& operator=(const AuthObjRReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuthObjRReply& operator=(AuthObjRReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuthObjRReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuthObjRReply* internal_default_instance() {
    return reinterpret_cast<const AuthObjRReply*>(
        &_AuthObjRReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(AuthObjRReply& a, AuthObjRReply& b) { a.Swap(&b); }
  inline void Swap(AuthObjRReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuthObjRReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuthObjRReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AuthObjRReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AuthObjRReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AuthObjRReply& from) { AuthObjRReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AuthObjRReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.AuthObjRReply"; }

 protected:
  explicit AuthObjRReply(::google::protobuf::Arena* arena);
  AuthObjRReply(::google::protobuf::Arena* arena, const AuthObjRReply& from);
  AuthObjRReply(::google::protobuf::Arena* arena, AuthObjRReply&& from) noexcept
      : AuthObjRReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdObjFieldNumber = 1,
  };
  // uint64 idObj = 1;
  void clear_idobj() ;
  ::uint64_t idobj() const;
  void set_idobj(::uint64_t value);

  private:
  ::uint64_t _internal_idobj() const;
  void _internal_set_idobj(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:client_router.AuthObjRReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AuthObjRReply_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AuthObjRReply& from_msg);
    ::uint64_t idobj_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};
// -------------------------------------------------------------------

class AddCommandGameRRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.AddCommandGameRRequest) */ {
 public:
  inline AddCommandGameRRequest() : AddCommandGameRRequest(nullptr) {}
  ~AddCommandGameRRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddCommandGameRRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline AddCommandGameRRequest(const AddCommandGameRRequest& from) : AddCommandGameRRequest(nullptr, from) {}
  inline AddCommandGameRRequest(AddCommandGameRRequest&& from) noexcept
      : AddCommandGameRRequest(nullptr, std::move(from)) {}
  inline AddCommandGameRRequest& operator=(const AddCommandGameRRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddCommandGameRRequest& operator=(AddCommandGameRRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddCommandGameRRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddCommandGameRRequest* internal_default_instance() {
    return reinterpret_cast<const AddCommandGameRRequest*>(
        &_AddCommandGameRRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(AddCommandGameRRequest& a, AddCommandGameRRequest& b) { a.Swap(&b); }
  inline void Swap(AddCommandGameRRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddCommandGameRRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddCommandGameRRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AddCommandGameRRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AddCommandGameRRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AddCommandGameRRequest& from) { AddCommandGameRRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AddCommandGameRRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.AddCommandGameRRequest"; }

 protected:
  explicit AddCommandGameRRequest(::google::protobuf::Arena* arena);
  AddCommandGameRRequest(::google::protobuf::Arena* arena, const AddCommandGameRRequest& from);
  AddCommandGameRRequest(::google::protobuf::Arena* arena, AddCommandGameRRequest&& from) noexcept
      : AddCommandGameRRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTypeCommandFieldNumber = 4,
    kArgsFieldNumber = 5,
    kIdSenderFieldNumber = 1,
    kIdGameFieldNumber = 2,
    kIdObjFieldNumber = 3,
  };
  // string TypeCommand = 4;
  void clear_typecommand() ;
  const std::string& typecommand() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_typecommand(Arg_&& arg, Args_... args);
  std::string* mutable_typecommand();
  PROTOBUF_NODISCARD std::string* release_typecommand();
  void set_allocated_typecommand(std::string* value);

  private:
  const std::string& _internal_typecommand() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_typecommand(
      const std::string& value);
  std::string* _internal_mutable_typecommand();

  public:
  // string args = 5;
  void clear_args() ;
  const std::string& args() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_args(Arg_&& arg, Args_... args);
  std::string* mutable_args();
  PROTOBUF_NODISCARD std::string* release_args();
  void set_allocated_args(std::string* value);

  private:
  const std::string& _internal_args() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_args(
      const std::string& value);
  std::string* _internal_mutable_args();

  public:
  // uint64 idSender = 1;
  void clear_idsender() ;
  ::uint64_t idsender() const;
  void set_idsender(::uint64_t value);

  private:
  ::uint64_t _internal_idsender() const;
  void _internal_set_idsender(::uint64_t value);

  public:
  // uint64 idGame = 2;
  void clear_idgame() ;
  ::uint64_t idgame() const;
  void set_idgame(::uint64_t value);

  private:
  ::uint64_t _internal_idgame() const;
  void _internal_set_idgame(::uint64_t value);

  public:
  // uint64 idObj = 3;
  void clear_idobj() ;
  ::uint64_t idobj() const;
  void set_idobj(::uint64_t value);

  private:
  ::uint64_t _internal_idobj() const;
  void _internal_set_idobj(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:client_router.AddCommandGameRRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      60, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AddCommandGameRRequest_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AddCommandGameRRequest& from_msg);
    ::google::protobuf::internal::ArenaStringPtr typecommand_;
    ::google::protobuf::internal::ArenaStringPtr args_;
    ::uint64_t idsender_;
    ::uint64_t idgame_;
    ::uint64_t idobj_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};
// -------------------------------------------------------------------

class AddCommandGameRReply final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:client_router.AddCommandGameRReply) */ {
 public:
  inline AddCommandGameRReply() : AddCommandGameRReply(nullptr) {}
  ~AddCommandGameRReply() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddCommandGameRReply(
      ::google::protobuf::internal::ConstantInitialized);

  inline AddCommandGameRReply(const AddCommandGameRReply& from) : AddCommandGameRReply(nullptr, from) {}
  inline AddCommandGameRReply(AddCommandGameRReply&& from) noexcept
      : AddCommandGameRReply(nullptr, std::move(from)) {}
  inline AddCommandGameRReply& operator=(const AddCommandGameRReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddCommandGameRReply& operator=(AddCommandGameRReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddCommandGameRReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const AddCommandGameRReply* internal_default_instance() {
    return reinterpret_cast<const AddCommandGameRReply*>(
        &_AddCommandGameRReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(AddCommandGameRReply& a, AddCommandGameRReply& b) { a.Swap(&b); }
  inline void Swap(AddCommandGameRReply* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddCommandGameRReply* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddCommandGameRReply* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<AddCommandGameRReply>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AddCommandGameRReply& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AddCommandGameRReply& from) { AddCommandGameRReply::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(AddCommandGameRReply* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "client_router.AddCommandGameRReply"; }

 protected:
  explicit AddCommandGameRReply(::google::protobuf::Arena* arena);
  AddCommandGameRReply(::google::protobuf::Arena* arena, const AddCommandGameRReply& from);
  AddCommandGameRReply(::google::protobuf::Arena* arena, AddCommandGameRReply&& from) noexcept
      : AddCommandGameRReply(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjParamsFieldNumber = 1,
  };
  // string objParams = 1;
  void clear_objparams() ;
  const std::string& objparams() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_objparams(Arg_&& arg, Args_... args);
  std::string* mutable_objparams();
  PROTOBUF_NODISCARD std::string* release_objparams();
  void set_allocated_objparams(std::string* value);

  private:
  const std::string& _internal_objparams() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_objparams(
      const std::string& value);
  std::string* _internal_mutable_objparams();

  public:
  // @@protoc_insertion_point(class_scope:client_router.AddCommandGameRReply)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      52, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_AddCommandGameRReply_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const AddCommandGameRReply& from_msg);
    ::google::protobuf::internal::ArenaStringPtr objparams_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_client_5frouter_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AuthObjRRequest

// int32 typeRegister = 1;
inline void AuthObjRRequest::clear_typeregister() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typeregister_ = 0;
}
inline ::int32_t AuthObjRRequest::typeregister() const {
  // @@protoc_insertion_point(field_get:client_router.AuthObjRRequest.typeRegister)
  return _internal_typeregister();
}
inline void AuthObjRRequest::set_typeregister(::int32_t value) {
  _internal_set_typeregister(value);
  // @@protoc_insertion_point(field_set:client_router.AuthObjRRequest.typeRegister)
}
inline ::int32_t AuthObjRRequest::_internal_typeregister() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.typeregister_;
}
inline void AuthObjRRequest::_internal_set_typeregister(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typeregister_ = value;
}

// -------------------------------------------------------------------

// AuthObjRReply

// uint64 idObj = 1;
inline void AuthObjRReply::clear_idobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = ::uint64_t{0u};
}
inline ::uint64_t AuthObjRReply::idobj() const {
  // @@protoc_insertion_point(field_get:client_router.AuthObjRReply.idObj)
  return _internal_idobj();
}
inline void AuthObjRReply::set_idobj(::uint64_t value) {
  _internal_set_idobj(value);
  // @@protoc_insertion_point(field_set:client_router.AuthObjRReply.idObj)
}
inline ::uint64_t AuthObjRReply::_internal_idobj() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idobj_;
}
inline void AuthObjRReply::_internal_set_idobj(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = value;
}

// -------------------------------------------------------------------

// StartNewGameRRequest

// uint64 idObj = 1;
inline void StartNewGameRRequest::clear_idobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = ::uint64_t{0u};
}
inline ::uint64_t StartNewGameRRequest::idobj() const {
  // @@protoc_insertion_point(field_get:client_router.StartNewGameRRequest.idObj)
  return _internal_idobj();
}
inline void StartNewGameRRequest::set_idobj(::uint64_t value) {
  _internal_set_idobj(value);
  // @@protoc_insertion_point(field_set:client_router.StartNewGameRRequest.idObj)
}
inline ::uint64_t StartNewGameRRequest::_internal_idobj() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idobj_;
}
inline void StartNewGameRRequest::_internal_set_idobj(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = value;
}

// string idOtherObj = 3;
inline void StartNewGameRRequest::clear_idotherobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idotherobj_.ClearToEmpty();
}
inline const std::string& StartNewGameRRequest::idotherobj() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:client_router.StartNewGameRRequest.idOtherObj)
  return _internal_idotherobj();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void StartNewGameRRequest::set_idotherobj(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idotherobj_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:client_router.StartNewGameRRequest.idOtherObj)
}
inline std::string* StartNewGameRRequest::mutable_idotherobj() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_idotherobj();
  // @@protoc_insertion_point(field_mutable:client_router.StartNewGameRRequest.idOtherObj)
  return _s;
}
inline const std::string& StartNewGameRRequest::_internal_idotherobj() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idotherobj_.Get();
}
inline void StartNewGameRRequest::_internal_set_idotherobj(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idotherobj_.Set(value, GetArena());
}
inline std::string* StartNewGameRRequest::_internal_mutable_idotherobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.idotherobj_.Mutable( GetArena());
}
inline std::string* StartNewGameRRequest::release_idotherobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:client_router.StartNewGameRRequest.idOtherObj)
  return _impl_.idotherobj_.Release();
}
inline void StartNewGameRRequest::set_allocated_idotherobj(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idotherobj_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.idotherobj_.IsDefault()) {
          _impl_.idotherobj_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:client_router.StartNewGameRRequest.idOtherObj)
}

// string otherArgs = 4;
inline void StartNewGameRRequest::clear_otherargs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.otherargs_.ClearToEmpty();
}
inline const std::string& StartNewGameRRequest::otherargs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:client_router.StartNewGameRRequest.otherArgs)
  return _internal_otherargs();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void StartNewGameRRequest::set_otherargs(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.otherargs_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:client_router.StartNewGameRRequest.otherArgs)
}
inline std::string* StartNewGameRRequest::mutable_otherargs() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_otherargs();
  // @@protoc_insertion_point(field_mutable:client_router.StartNewGameRRequest.otherArgs)
  return _s;
}
inline const std::string& StartNewGameRRequest::_internal_otherargs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.otherargs_.Get();
}
inline void StartNewGameRRequest::_internal_set_otherargs(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.otherargs_.Set(value, GetArena());
}
inline std::string* StartNewGameRRequest::_internal_mutable_otherargs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.otherargs_.Mutable( GetArena());
}
inline std::string* StartNewGameRRequest::release_otherargs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:client_router.StartNewGameRRequest.otherArgs)
  return _impl_.otherargs_.Release();
}
inline void StartNewGameRRequest::set_allocated_otherargs(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.otherargs_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.otherargs_.IsDefault()) {
          _impl_.otherargs_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:client_router.StartNewGameRRequest.otherArgs)
}

// -------------------------------------------------------------------

// StartNewGameRReply

// bool resultCheck = 1;
inline void StartNewGameRReply::clear_resultcheck() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resultcheck_ = false;
}
inline bool StartNewGameRReply::resultcheck() const {
  // @@protoc_insertion_point(field_get:client_router.StartNewGameRReply.resultCheck)
  return _internal_resultcheck();
}
inline void StartNewGameRReply::set_resultcheck(bool value) {
  _internal_set_resultcheck(value);
  // @@protoc_insertion_point(field_set:client_router.StartNewGameRReply.resultCheck)
}
inline bool StartNewGameRReply::_internal_resultcheck() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resultcheck_;
}
inline void StartNewGameRReply::_internal_set_resultcheck(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resultcheck_ = value;
}

// uint64 idGame = 2;
inline void StartNewGameRReply::clear_idgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = ::uint64_t{0u};
}
inline ::uint64_t StartNewGameRReply::idgame() const {
  // @@protoc_insertion_point(field_get:client_router.StartNewGameRReply.idGame)
  return _internal_idgame();
}
inline void StartNewGameRReply::set_idgame(::uint64_t value) {
  _internal_set_idgame(value);
  // @@protoc_insertion_point(field_set:client_router.StartNewGameRReply.idGame)
}
inline ::uint64_t StartNewGameRReply::_internal_idgame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idgame_;
}
inline void StartNewGameRReply::_internal_set_idgame(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = value;
}

// -------------------------------------------------------------------

// AddCommandGameRRequest

// uint64 idSender = 1;
inline void AddCommandGameRRequest::clear_idsender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idsender_ = ::uint64_t{0u};
}
inline ::uint64_t AddCommandGameRRequest::idsender() const {
  // @@protoc_insertion_point(field_get:client_router.AddCommandGameRRequest.idSender)
  return _internal_idsender();
}
inline void AddCommandGameRRequest::set_idsender(::uint64_t value) {
  _internal_set_idsender(value);
  // @@protoc_insertion_point(field_set:client_router.AddCommandGameRRequest.idSender)
}
inline ::uint64_t AddCommandGameRRequest::_internal_idsender() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idsender_;
}
inline void AddCommandGameRRequest::_internal_set_idsender(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idsender_ = value;
}

// uint64 idGame = 2;
inline void AddCommandGameRRequest::clear_idgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = ::uint64_t{0u};
}
inline ::uint64_t AddCommandGameRRequest::idgame() const {
  // @@protoc_insertion_point(field_get:client_router.AddCommandGameRRequest.idGame)
  return _internal_idgame();
}
inline void AddCommandGameRRequest::set_idgame(::uint64_t value) {
  _internal_set_idgame(value);
  // @@protoc_insertion_point(field_set:client_router.AddCommandGameRRequest.idGame)
}
inline ::uint64_t AddCommandGameRRequest::_internal_idgame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idgame_;
}
inline void AddCommandGameRRequest::_internal_set_idgame(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = value;
}

// uint64 idObj = 3;
inline void AddCommandGameRRequest::clear_idobj() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = ::uint64_t{0u};
}
inline ::uint64_t AddCommandGameRRequest::idobj() const {
  // @@protoc_insertion_point(field_get:client_router.AddCommandGameRRequest.idObj)
  return _internal_idobj();
}
inline void AddCommandGameRRequest::set_idobj(::uint64_t value) {
  _internal_set_idobj(value);
  // @@protoc_insertion_point(field_set:client_router.AddCommandGameRRequest.idObj)
}
inline ::uint64_t AddCommandGameRRequest::_internal_idobj() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idobj_;
}
inline void AddCommandGameRRequest::_internal_set_idobj(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idobj_ = value;
}

// string TypeCommand = 4;
inline void AddCommandGameRRequest::clear_typecommand() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typecommand_.ClearToEmpty();
}
inline const std::string& AddCommandGameRRequest::typecommand() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:client_router.AddCommandGameRRequest.TypeCommand)
  return _internal_typecommand();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AddCommandGameRRequest::set_typecommand(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typecommand_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:client_router.AddCommandGameRRequest.TypeCommand)
}
inline std::string* AddCommandGameRRequest::mutable_typecommand() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_typecommand();
  // @@protoc_insertion_point(field_mutable:client_router.AddCommandGameRRequest.TypeCommand)
  return _s;
}
inline const std::string& AddCommandGameRRequest::_internal_typecommand() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.typecommand_.Get();
}
inline void AddCommandGameRRequest::_internal_set_typecommand(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typecommand_.Set(value, GetArena());
}
inline std::string* AddCommandGameRRequest::_internal_mutable_typecommand() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.typecommand_.Mutable( GetArena());
}
inline std::string* AddCommandGameRRequest::release_typecommand() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:client_router.AddCommandGameRRequest.TypeCommand)
  return _impl_.typecommand_.Release();
}
inline void AddCommandGameRRequest::set_allocated_typecommand(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.typecommand_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.typecommand_.IsDefault()) {
          _impl_.typecommand_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:client_router.AddCommandGameRRequest.TypeCommand)
}

// string args = 5;
inline void AddCommandGameRRequest::clear_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.args_.ClearToEmpty();
}
inline const std::string& AddCommandGameRRequest::args() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:client_router.AddCommandGameRRequest.args)
  return _internal_args();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AddCommandGameRRequest::set_args(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.args_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:client_router.AddCommandGameRRequest.args)
}
inline std::string* AddCommandGameRRequest::mutable_args() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_args();
  // @@protoc_insertion_point(field_mutable:client_router.AddCommandGameRRequest.args)
  return _s;
}
inline const std::string& AddCommandGameRRequest::_internal_args() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.args_.Get();
}
inline void AddCommandGameRRequest::_internal_set_args(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.args_.Set(value, GetArena());
}
inline std::string* AddCommandGameRRequest::_internal_mutable_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.args_.Mutable( GetArena());
}
inline std::string* AddCommandGameRRequest::release_args() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:client_router.AddCommandGameRRequest.args)
  return _impl_.args_.Release();
}
inline void AddCommandGameRRequest::set_allocated_args(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.args_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.args_.IsDefault()) {
          _impl_.args_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:client_router.AddCommandGameRRequest.args)
}

// -------------------------------------------------------------------

// AddCommandGameRReply

// string objParams = 1;
inline void AddCommandGameRReply::clear_objparams() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objparams_.ClearToEmpty();
}
inline const std::string& AddCommandGameRReply::objparams() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:client_router.AddCommandGameRReply.objParams)
  return _internal_objparams();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AddCommandGameRReply::set_objparams(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objparams_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:client_router.AddCommandGameRReply.objParams)
}
inline std::string* AddCommandGameRReply::mutable_objparams() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_objparams();
  // @@protoc_insertion_point(field_mutable:client_router.AddCommandGameRReply.objParams)
  return _s;
}
inline const std::string& AddCommandGameRReply::_internal_objparams() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.objparams_.Get();
}
inline void AddCommandGameRReply::_internal_set_objparams(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objparams_.Set(value, GetArena());
}
inline std::string* AddCommandGameRReply::_internal_mutable_objparams() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.objparams_.Mutable( GetArena());
}
inline std::string* AddCommandGameRReply::release_objparams() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:client_router.AddCommandGameRReply.objParams)
  return _impl_.objparams_.Release();
}
inline void AddCommandGameRReply::set_allocated_objparams(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objparams_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.objparams_.IsDefault()) {
          _impl_.objparams_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:client_router.AddCommandGameRReply.objParams)
}

// -------------------------------------------------------------------

// StopGameRRequest

// uint64 idSender = 1;
inline void StopGameRRequest::clear_idsender() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idsender_ = ::uint64_t{0u};
}
inline ::uint64_t StopGameRRequest::idsender() const {
  // @@protoc_insertion_point(field_get:client_router.StopGameRRequest.idSender)
  return _internal_idsender();
}
inline void StopGameRRequest::set_idsender(::uint64_t value) {
  _internal_set_idsender(value);
  // @@protoc_insertion_point(field_set:client_router.StopGameRRequest.idSender)
}
inline ::uint64_t StopGameRRequest::_internal_idsender() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idsender_;
}
inline void StopGameRRequest::_internal_set_idsender(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idsender_ = value;
}

// uint64 idGame = 2;
inline void StopGameRRequest::clear_idgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = ::uint64_t{0u};
}
inline ::uint64_t StopGameRRequest::idgame() const {
  // @@protoc_insertion_point(field_get:client_router.StopGameRRequest.idGame)
  return _internal_idgame();
}
inline void StopGameRRequest::set_idgame(::uint64_t value) {
  _internal_set_idgame(value);
  // @@protoc_insertion_point(field_set:client_router.StopGameRRequest.idGame)
}
inline ::uint64_t StopGameRRequest::_internal_idgame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idgame_;
}
inline void StopGameRRequest::_internal_set_idgame(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = value;
}

// -------------------------------------------------------------------

// StopGameRReply

// bool resultCheck = 1;
inline void StopGameRReply::clear_resultcheck() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resultcheck_ = false;
}
inline bool StopGameRReply::resultcheck() const {
  // @@protoc_insertion_point(field_get:client_router.StopGameRReply.resultCheck)
  return _internal_resultcheck();
}
inline void StopGameRReply::set_resultcheck(bool value) {
  _internal_set_resultcheck(value);
  // @@protoc_insertion_point(field_set:client_router.StopGameRReply.resultCheck)
}
inline bool StopGameRReply::_internal_resultcheck() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.resultcheck_;
}
inline void StopGameRReply::_internal_set_resultcheck(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.resultcheck_ = value;
}

// -------------------------------------------------------------------

// GetInfGameRRequest

// uint64 idGame = 1;
inline void GetInfGameRRequest::clear_idgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = ::uint64_t{0u};
}
inline ::uint64_t GetInfGameRRequest::idgame() const {
  // @@protoc_insertion_point(field_get:client_router.GetInfGameRRequest.idGame)
  return _internal_idgame();
}
inline void GetInfGameRRequest::set_idgame(::uint64_t value) {
  _internal_set_idgame(value);
  // @@protoc_insertion_point(field_set:client_router.GetInfGameRRequest.idGame)
}
inline ::uint64_t GetInfGameRRequest::_internal_idgame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.idgame_;
}
inline void GetInfGameRRequest::_internal_set_idgame(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.idgame_ = value;
}

// -------------------------------------------------------------------

// GetInfGameRReply

// string infGame = 1;
inline void GetInfGameRReply::clear_infgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.infgame_.ClearToEmpty();
}
inline const std::string& GetInfGameRReply::infgame() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:client_router.GetInfGameRReply.infGame)
  return _internal_infgame();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void GetInfGameRReply::set_infgame(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.infgame_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:client_router.GetInfGameRReply.infGame)
}
inline std::string* GetInfGameRReply::mutable_infgame() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_infgame();
  // @@protoc_insertion_point(field_mutable:client_router.GetInfGameRReply.infGame)
  return _s;
}
inline const std::string& GetInfGameRReply::_internal_infgame() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.infgame_.Get();
}
inline void GetInfGameRReply::_internal_set_infgame(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.infgame_.Set(value, GetArena());
}
inline std::string* GetInfGameRReply::_internal_mutable_infgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.infgame_.Mutable( GetArena());
}
inline std::string* GetInfGameRReply::release_infgame() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:client_router.GetInfGameRReply.infGame)
  return _impl_.infgame_.Release();
}
inline void GetInfGameRReply::set_allocated_infgame(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.infgame_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.infgame_.IsDefault()) {
          _impl_.infgame_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:client_router.GetInfGameRReply.infGame)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace client_router


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_client_5frouter_2eproto_2epb_2eh
