// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: authorization.proto
#ifndef GRPC_authorization_2eproto__INCLUDED
#define GRPC_authorization_2eproto__INCLUDED

#include "authorization.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace authorization {

// The greeting service definition.
class Authorization final {
 public:
  static constexpr char const* service_full_name() {
    return "authorization.Authorization";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::authorization::CheckAuthReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::authorization::CheckAuthReply>> AsyncCheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::authorization::CheckAuthReply>>(AsyncCheckAuthorizationObjRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::authorization::CheckAuthReply>> PrepareAsyncCheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::authorization::CheckAuthReply>>(PrepareAsyncCheckAuthorizationObjRaw(context, request, cq));
    }
    virtual ::grpc::Status AuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::authorization::AuthObjReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::authorization::AuthObjReply>> AsyncAuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::authorization::AuthObjReply>>(AsyncAuthorizationObjRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::authorization::AuthObjReply>> PrepareAsyncAuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::authorization::AuthObjReply>>(PrepareAsyncAuthorizationObjRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest* request, ::authorization::CheckAuthReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest* request, ::authorization::CheckAuthReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest* request, ::authorization::AuthObjReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest* request, ::authorization::AuthObjReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::authorization::CheckAuthReply>* AsyncCheckAuthorizationObjRaw(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::authorization::CheckAuthReply>* PrepareAsyncCheckAuthorizationObjRaw(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::authorization::AuthObjReply>* AsyncAuthorizationObjRaw(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::authorization::AuthObjReply>* PrepareAsyncAuthorizationObjRaw(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::authorization::CheckAuthReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::authorization::CheckAuthReply>> AsyncCheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::authorization::CheckAuthReply>>(AsyncCheckAuthorizationObjRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::authorization::CheckAuthReply>> PrepareAsyncCheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::authorization::CheckAuthReply>>(PrepareAsyncCheckAuthorizationObjRaw(context, request, cq));
    }
    ::grpc::Status AuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::authorization::AuthObjReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::authorization::AuthObjReply>> AsyncAuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::authorization::AuthObjReply>>(AsyncAuthorizationObjRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::authorization::AuthObjReply>> PrepareAsyncAuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::authorization::AuthObjReply>>(PrepareAsyncAuthorizationObjRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest* request, ::authorization::CheckAuthReply* response, std::function<void(::grpc::Status)>) override;
      void CheckAuthorizationObj(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest* request, ::authorization::CheckAuthReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest* request, ::authorization::AuthObjReply* response, std::function<void(::grpc::Status)>) override;
      void AuthorizationObj(::grpc::ClientContext* context, const ::authorization::AuthObjRequest* request, ::authorization::AuthObjReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::authorization::CheckAuthReply>* AsyncCheckAuthorizationObjRaw(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::authorization::CheckAuthReply>* PrepareAsyncCheckAuthorizationObjRaw(::grpc::ClientContext* context, const ::authorization::CheckAuthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::authorization::AuthObjReply>* AsyncAuthorizationObjRaw(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::authorization::AuthObjReply>* PrepareAsyncAuthorizationObjRaw(::grpc::ClientContext* context, const ::authorization::AuthObjRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CheckAuthorizationObj_;
    const ::grpc::internal::RpcMethod rpcmethod_AuthorizationObj_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CheckAuthorizationObj(::grpc::ServerContext* context, const ::authorization::CheckAuthRequest* request, ::authorization::CheckAuthReply* response);
    virtual ::grpc::Status AuthorizationObj(::grpc::ServerContext* context, const ::authorization::AuthObjRequest* request, ::authorization::AuthObjReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CheckAuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CheckAuthorizationObj() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CheckAuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::CheckAuthRequest* /*request*/, ::authorization::CheckAuthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckAuthorizationObj(::grpc::ServerContext* context, ::authorization::CheckAuthRequest* request, ::grpc::ServerAsyncResponseWriter< ::authorization::CheckAuthReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AuthorizationObj() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_AuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::AuthObjRequest* /*request*/, ::authorization::AuthObjReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthorizationObj(::grpc::ServerContext* context, ::authorization::AuthObjRequest* request, ::grpc::ServerAsyncResponseWriter< ::authorization::AuthObjReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CheckAuthorizationObj<WithAsyncMethod_AuthorizationObj<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CheckAuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CheckAuthorizationObj() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::authorization::CheckAuthRequest, ::authorization::CheckAuthReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::authorization::CheckAuthRequest* request, ::authorization::CheckAuthReply* response) { return this->CheckAuthorizationObj(context, request, response); }));}
    void SetMessageAllocatorFor_CheckAuthorizationObj(
        ::grpc::MessageAllocator< ::authorization::CheckAuthRequest, ::authorization::CheckAuthReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::authorization::CheckAuthRequest, ::authorization::CheckAuthReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CheckAuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::CheckAuthRequest* /*request*/, ::authorization::CheckAuthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckAuthorizationObj(
      ::grpc::CallbackServerContext* /*context*/, const ::authorization::CheckAuthRequest* /*request*/, ::authorization::CheckAuthReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AuthorizationObj() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::authorization::AuthObjRequest, ::authorization::AuthObjReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::authorization::AuthObjRequest* request, ::authorization::AuthObjReply* response) { return this->AuthorizationObj(context, request, response); }));}
    void SetMessageAllocatorFor_AuthorizationObj(
        ::grpc::MessageAllocator< ::authorization::AuthObjRequest, ::authorization::AuthObjReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::authorization::AuthObjRequest, ::authorization::AuthObjReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::AuthObjRequest* /*request*/, ::authorization::AuthObjReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthorizationObj(
      ::grpc::CallbackServerContext* /*context*/, const ::authorization::AuthObjRequest* /*request*/, ::authorization::AuthObjReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CheckAuthorizationObj<WithCallbackMethod_AuthorizationObj<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CheckAuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CheckAuthorizationObj() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CheckAuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::CheckAuthRequest* /*request*/, ::authorization::CheckAuthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AuthorizationObj() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_AuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::AuthObjRequest* /*request*/, ::authorization::AuthObjReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CheckAuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CheckAuthorizationObj() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CheckAuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::CheckAuthRequest* /*request*/, ::authorization::CheckAuthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCheckAuthorizationObj(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AuthorizationObj() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_AuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::AuthObjRequest* /*request*/, ::authorization::AuthObjReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAuthorizationObj(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CheckAuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CheckAuthorizationObj() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CheckAuthorizationObj(context, request, response); }));
    }
    ~WithRawCallbackMethod_CheckAuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CheckAuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::CheckAuthRequest* /*request*/, ::authorization::CheckAuthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CheckAuthorizationObj(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AuthorizationObj() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AuthorizationObj(context, request, response); }));
    }
    ~WithRawCallbackMethod_AuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::AuthObjRequest* /*request*/, ::authorization::AuthObjReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AuthorizationObj(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CheckAuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CheckAuthorizationObj() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::authorization::CheckAuthRequest, ::authorization::CheckAuthReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::authorization::CheckAuthRequest, ::authorization::CheckAuthReply>* streamer) {
                       return this->StreamedCheckAuthorizationObj(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CheckAuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CheckAuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::CheckAuthRequest* /*request*/, ::authorization::CheckAuthReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCheckAuthorizationObj(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::authorization::CheckAuthRequest,::authorization::CheckAuthReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AuthorizationObj : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AuthorizationObj() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::authorization::AuthObjRequest, ::authorization::AuthObjReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::authorization::AuthObjRequest, ::authorization::AuthObjReply>* streamer) {
                       return this->StreamedAuthorizationObj(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AuthorizationObj() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AuthorizationObj(::grpc::ServerContext* /*context*/, const ::authorization::AuthObjRequest* /*request*/, ::authorization::AuthObjReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAuthorizationObj(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::authorization::AuthObjRequest,::authorization::AuthObjReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CheckAuthorizationObj<WithStreamedUnaryMethod_AuthorizationObj<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CheckAuthorizationObj<WithStreamedUnaryMethod_AuthorizationObj<Service > > StreamedService;
};

}  // namespace authorization


#endif  // GRPC_authorization_2eproto__INCLUDED
